### ISSUE TITLE
Any chance of making light theme match guidelines?

### ISSUE THREAD

**Issue by jahirfiquitiva** [dodgingpixels/Optic#14]
Like making it follow the guidelines? https://material.io/guidelines/style/color.html#color-themes

**Comment by staber** [comment]
I'm using #FAFAFA for the light theme which is the default Material Light color.

**Comment by jahirfiquitiva** [comment]
@staber  Yep, but toolbar color should be #f5f5f5 and status bar #e0e0e0 ... also, consider adding lightStatusBar flag on Android 6+

**Comment by jahirfiquitiva** [comment]
@staber Updated the title

Btw, just checked the app using a color picker and found it uses #e0e0e0 as background color, where it should be #fafafa as you said, this is only in the main view and albums view.

**Comment by staber** [comment]
fixed in v0.5.0
