### ISSUE TITLE
Please add a button to quickly launch camera from app

### ISSUE THREAD

**Issue by jahirfiquitiva** [dodgingpixels/Optic#18]
Like a fab in the main view. Thanks.

**Comment by staber** [comment]
There won't be a FAB or Nav Drawer in Optic. I'll consider a menu item though.

**Comment by jahirfiquitiva** [comment]
@staber 

Ok. Then can the main menu show the primary actions in toolbar?

For example, there's currently 'translate' and 'bug report'. I think those should be replaced with 'search' and 'sort'.

Thanks.

**Comment by staber** [comment]
The translate and bug are only for the beta version. There will be different items for the final release.
