### ISSUE TITLE
Toolbar icons remain grey after theme change

### ISSUE THREAD

**Issue by jahirfiquitiva** [dodgingpixels/Optic#19]
Specifically the translate and bug report icons

**Comment by staber** [comment]
I'm not able to reproduce this.

**Comment by jahirfiquitiva** [comment]
@staber
This is how they look for me in dark theme
![screenshot_20170726-205314-01](https://user-images.githubusercontent.com/10360816/28651193-f3aac29e-7245-11e7-94be-3e8e232fe077.png)

**Comment by staber** [comment]
This may be a system bug. What OS version are you on?

**Comment by jahirfiquitiva** [comment]
@staber 
I'm using Android 7.1.2

**Comment by jahirfiquitiva** [comment]
This seems to be fixed for me in last update.

**Comment by staber** [comment]
ok, let me know if you notice it again.
