### ISSUE TITLE
Bottom sheet is white in all themes

### ISSUE THREAD

**Issue by jahirfiquitiva** [dodgingpixels/Optic#20]
I think it would be nice if it matched the current theme

**Comment by jahirfiquitiva** [comment]
The same applies to overflow menu

**Comment by staber** [comment]
bottom sheet was intended this way because a dark sheet would clash with the black image background. 
Overflow is part of the theme and is not really intended to change dynamically.

**Comment by jahirfiquitiva** [comment]
I think both things should react to the theme. Also, both should use the card/dialog color for respective theme, so they wouldn't ever clash with the black background since they will never be black.

**Comment by jahirfiquitiva** [comment]
In addition to bottom sheet and overflow menu, dialogs are also light in other themes. As I mentioned already, I think all these should be affected by the current theme
