### ISSUE TITLE
Change 3-dots icon for a fab

### ISSUE THREAD

**Issue by jahirfiquitiva** [dodgingpixels/Optic#24]
In the picture viewer, the 3 dots icon is too small and sometimes hard to see on light pictures.
I think a fab with look better, since it's bigger.

**Comment by staber** [comment]
I think fab's are too distracting and that menu is not the primary action for that screen.

**Comment by jahirfiquitiva** [comment]
@staber 
The fab could have a '+' icon. It could also be hidden just like toolbar.

Anyways, if you don't want it, it's ok. But then do something with the current menu icon.

1. They usually go in toolbar. (Moving it there could work.)
2. Is too small
3. It isn't always visible enough. Sometimes I think it even isn't there.

**Comment by staber** [comment]
I'll look into modifying the color. I don't plan on moving it to the toolbar for _reachability_ reasons though. That's why it's on the bottom to begin with.

**Comment by jahirfiquitiva** [comment]
And that's why FABs exist too.

**Comment by staber** [comment]
[From the guidelines](https://material.io/guidelines/components/buttons-floating-action-button.html#buttons-floating-action-button-floating-action-button)

> Not every screen needs a floating action button. A floating action button represents the primary action in an application.

> The primary action is to touch images in a gallery, so no button is needed.

....But, further down the page they also use Fab's on gallery samples

**Comment by jahirfiquitiva** [comment]
@staber 

Yeah, that's what guidelines say, but I think it means 'in an activity/section' instead of application.

For example, the albums view is fine as it is. No button is needed.

But the picture viewer deserves to have it.

Also from guidelines:

> Only one floating action button is recommended per screen to represent the most common action.

As you can read, they say 'screen' ..... The most common action in the viewer, is to open the bottom sheet, but the dots icon is way too small, a fab would be good there.
