### ISSUE TITLE
Add a gradient to picture viewer toolbar

### ISSUE THREAD

**Issue by jahirfiquitiva** [dodgingpixels/Optic#25]
That way, you can ensure toolbar icons visibility in all pictures

**Comment by staber** [comment]
I'll check into it but gradients can sometimes cause visual artifacts. It puts unnecessary strain on the GPU for a minor benefit.

**Comment by jahirfiquitiva** [comment]
@staber 
I don't think 1 single gradient in the whole app could cause significant negative effects.

**Comment by staber** [comment]
fixed in 0.7.0-BETA
