### ISSUE TITLE
Password not working until 'for specific functions' is enabled

### ISSUE THREAD

**Issue by jahirfiquitiva** [dodgingpixels/Optic#27]
I think the default behavior should be that, if one sets a password, all the functions should require it, unless one enables 'for specific functions' where one would disable only the ones one do not want to protect with password.

Otherwise, the 'set password' option basically serves no purpose.

(PS: Sorry for too many issues. I'm really liking this gallery app and would like it to be even better)

**Comment by staber** [comment]
This is a lose-lose, because someone else may only want a single security feature enabled and would then have to disable all the others. 
All of the toggles depend on 'set password' because the code needs to be setup first. Then 'Enable Passcode' is more like your master toggle.
