### ISSUE TITLE
Add refresh button or implement pictures refresh in onResume

### ISSUE THREAD

**Issue by jahirfiquitiva** [dodgingpixels/Optic#28]
That way one can always see an updated gallery.

For example, I took a screenshot, and didn't see it until I reopened the app

**Comment by staber** [comment]
I originally intended for manual refresh only but too many people wanted auto-refresh. I compromised and perform a refresh during onStart. I think a refresh during onResume would be very excessive, especially for people with large libraries.  
You can always perform a pull-to-refresh whenever you like.

**Comment by jahirfiquitiva** [comment]
@staber

Yeah, you're right, it might be a bit excessive ... Well, I didn't realize I could pull-to-refresh. Sorry and thanks :)
