### ISSUE TITLE
Change the style of 'share' and 'open with' menus

### ISSUE THREAD

**Issue by jahirfiquitiva** [dodgingpixels/Optic#29]
What I mean, is they currently show the 'Just once' and 'Always' buttons. I think it would be better if they never showed any of those and one could always choose a different app.

**Comment by focuslocked** [comment]
I second this.

**Comment by staber** [comment]
I just send the intent, the OS shows you a list of your apps that can receive that intent. You can choose an app every time by _Not_ clicking 'Always'. 
I'm not sure I understand your request.

**Comment by jahirfiquitiva** [comment]
@staber 

I'm almost sure there's another 'kind' of intent

This is how 'Camera Roll' does it:
![screenshot_20170726-224102](https://user-images.githubusercontent.com/10360816/28653582-f14f9660-7253-11e7-831b-f148b2376cd7.png)

**Comment by focuslocked** [comment]
This is how it should be. A gallery app should not ask for a default
sharing option! The "Just Once" and "Always” intents are meant for one time
selections where a default might need to be set.

**Comment by focuslocked** [comment]
Also, I almost forgot, Optic does not show up in the picker list, for
example, when trying to set a wallpaper.

**Comment by staber** [comment]
fixed in [v0.5.2](https://github.com/dodgingpixels/Optic/releases/tag/v0.5.2)
