### ISSUE TITLE
Fingerprint recognized text color is teal

### ISSUE THREAD

**Issue by jahirfiquitiva** [dodgingpixels/Optic#33]
![screenshot_20170726-222227](https://user-images.githubusercontent.com/10360816/28653449-3390a25e-7253-11e7-9906-25e471348d8c.png)

**Comment by staber** [comment]
This is also part of a library. However, I'm already using a custom fork of it anyways so I'll look at updating it.

**Comment by jahirfiquitiva** [comment]
@staber 
Ok thanks

**Comment by staber** [comment]
fixed in v0.5.1
