### ISSUE TITLE
The app doesn't recognise .webm files as video

### ISSUE THREAD

**Issue by BeardDesign1** [dodgingpixels/Optic#40]
title says it all

**Comment by staber** [comment]
Do you have any samples you'd like me to test with?

**Comment by BeardDesign1** [comment]
Here, use [this file](http://i.dont.have.a.beard-design.com/2w832ZQo.webm). It doesn't appear in the gallery at all, hope you can make it work ;)

**Comment by staber** [comment]
added in [v0.5.2](https://github.com/dodgingpixels/Optic/releases/tag/v0.5.2)
