### ISSUE TITLE
In landscape orientation, on-screen navigation bar covers the app's toolbar

### ISSUE THREAD

**Issue by lavglaab** [dodgingpixels/Optic#41]
Moto G5 Plus, Android 7.0.
Steps to reproduce: Open app, turn phone sideways

**Comment by cholohhp** [comment]
Hola, hace unos días compartí con ustedes un error al no poder usarlo el botón menú en la vista de una foto en modo horizontal. Estaba probando un poco y cuando abrimos la foto en modo vertical y giramos el equipo, ocurre dicho error, pero si entramos a la foto en modo horizontal de primera intención, el botón de acomoda. Igualmente, apenas puede apreciarse, está muy chico, poco visible. Lo demás está genial. Por ahora sigue siendo mi galería por defecto. Gracias!
_________________

**Comment by staber** [comment]
fixed in 0.7.0-BETA
