### ISSUE TITLE
Search doesn't work properly

### ISSUE THREAD

**Issue by jahirfiquitiva** [dodgingpixels/Optic#43]
- Does not always show results or takes long time to show them
- I think you should use `contains` method when checking for results. (In case you don't, which is what I think from the results I get).
- Search allows multiline. It allows pressing the enter key. You can use `EditorInfo.IME_ACTION_SEARCH` to fix this.

**Comment by staber** [comment]
1. Speed is subjective based on the number of files you have. It's searching live in a database.
2. It does use `contains`, it's also not case sensitive but it does require at least 2 characters and they must be [Latin-1](https://cs.stanford.edu/people/miles/iso8859.html)
3. This is updated for the next version.
