### ISSUE TITLE
Change color of multiple select mode

### ISSUE THREAD

**Issue by revanmj** [dodgingpixels/Optic#47]
Any chance you could change select mode to something more toned down than pink? Or at least do not fill entire screen with it :)

**Comment by staber** [comment]
This is based on the accent color of the app for now. 
I may make this part of an adjustable theme color in the future.

**Comment by revanmj** [comment]
In a meantime restricting color change to actionbar and status bar (leaving background dark/white depending on theme) would be nice :)

**Comment by staber** [comment]
added in 0.7.1
