### ISSUE TITLE
Optic Beta (BUG)

### ISSUE THREAD

**Issue by diegocl5** [dodgingpixels/Optic#48]
Motorola Moto G5 
Android 7.0
**SPANISH:**
El problema esta en la función de vault ya que al añadir fotos al vault, en la aplicación funciona como debería pero en otras aplicaciones si puedo ver las fotos que he ocultado en el vault, creo que esas fotos que se colocan en el vault no deberían verse en otras aplicaciones así como WhatsApp, Facebook, Instagram etc.

**ENGLISH:**
The problem is in the vault function since when adding photos to the vault, in the application it works as it should but in other applications I can see the photos that I have hidden in the vault, I think those photos that are placed in the vault are not They should be seen in other applications such as WhatsApp, Facebook, Instagram etc.

**Comment by staber** [comment]
The vault is only internal to Optic. This does not encrypt or hide the files from other apps. What it sounds like you're looking for is hiding the album(s). This will add a '.nomedia' file in the folder directory and makes  them hidden from other system apps.
