### ISSUE TITLE
Disable swap function to navigate album to home

### ISSUE THREAD

**Issue by rummanz** [dodgingpixels/Optic#56]
I like this gallery app a lot. This is one of the minimalist and smooth gallery app I have ever seen. I just dislike one function of this app and I think it's annoying to others. Which is swipe navigation between album to home. If you add a option to disable it, then it will be a great gallery app.

**Comment by staber** [comment]
Just to double check, you mean the swipe from left to right to close an album?

**Comment by rummanz** [comment]
Yeah.

**Comment by staber** [comment]
added in 0.7.1
